package ai

import "context"

// MenuGenerateParams contains user input and constraints for AI menu generation.
type MenuGenerateParams struct {
	Goal          string   `json:"goal"`           // "hemat" | "sehat" | "diet" | "bebas"
	BudgetAmount  int      `json:"budget_amount"`  // rupiah integer
	BudgetPeriod  string   `json:"budget_period"`  // "harian" | "mingguan"
	HouseholdSize int      `json:"household_size"` // number of people
	Restrictions  []string `json:"restrictions"`   // dietary restrictions / allergies
}

// MenuIngredient represents an individual ingredient in a recipe generated by AI.
type MenuIngredient struct {
	Name           string `json:"name"`
	Quantity       string `json:"quantity"`
	Unit           string `json:"unit"`
	EstimatedPrice int    `json:"estimated_price"`
	PriceSource    string `json:"price_source,omitempty"`
}

// MenuOption represents a single recommended recipe menu.
type MenuOption struct {
	RecipeName          string           `json:"recipe_name"`
	Description         string           `json:"description"`
	EstimatedTotalPrice int              `json:"estimated_total_price"`
	GoalTags            []string         `json:"goal_tags"`
	Ingredients         []MenuIngredient `json:"ingredients"`
}

// MenuOptions contains the list of recommended menu options (typically 3 options).
type MenuOptions struct {
	Options []MenuOption `json:"options"`
}

// AIProvider defines the common interface for AI models (OpenAI, Groq, Gemini, Claude, etc.).
type AIProvider interface {
	GenerateMenu(ctx context.Context, params MenuGenerateParams) (*MenuOptions, error)
}
